name: Security Scanning

on:
  workflow_call:

permissions:
  contents: read # This allows the workflow to read your repository's contents.
  security-events: write # This permission allows the workflow to upload security scan results to GitHub's Security tab.

jobs:
    
  gitleaks:
    name: Secret Scan - Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Gitleaks needs full history to scan all commits

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}